// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Hl0KmUFcLrsO6uRoLBT_JTT1MkOWJ6I',
    appId: '1:559044741521:web:822e62b9c0f0aedfa53230',
    messagingSenderId: '559044741521',
    projectId: 'marvel-wallpaper-app-7adbf',
    authDomain: 'marvel-wallpaper-app-7adbf.firebaseapp.com',
    storageBucket: 'marvel-wallpaper-app-7adbf.appspot.com',
    measurementId: 'G-H308MH44HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt6K6x348X-H2eRph2Qf-UD_0hhvuAH8U',
    appId: '1:559044741521:android:47f076079186d4f9a53230',
    messagingSenderId: '559044741521',
    projectId: 'marvel-wallpaper-app-7adbf',
    storageBucket: 'marvel-wallpaper-app-7adbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBScPuT8j8hX0-nYD6uH_uz1cWkaXAZEjY',
    appId: '1:559044741521:ios:b19014e827a91ebfa53230',
    messagingSenderId: '559044741521',
    projectId: 'marvel-wallpaper-app-7adbf',
    storageBucket: 'marvel-wallpaper-app-7adbf.appspot.com',
    iosClientId: '559044741521-bsrnk15j21ga0c9ssbdpkmlbbqcc0r5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBScPuT8j8hX0-nYD6uH_uz1cWkaXAZEjY',
    appId: '1:559044741521:ios:b19014e827a91ebfa53230',
    messagingSenderId: '559044741521',
    projectId: 'marvel-wallpaper-app-7adbf',
    storageBucket: 'marvel-wallpaper-app-7adbf.appspot.com',
    iosClientId: '559044741521-bsrnk15j21ga0c9ssbdpkmlbbqcc0r5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );
}
